"""Initial migration

Revision ID: fa10f710145b
Revises: 
Create Date: 2024-08-03 14:51:21.400999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa10f710145b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('holding_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('holding_id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('transactions',
    sa.Column('trans_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('trans_type', sa.Enum('buy', 'sell'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('trans_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('holdings')
    # ### end Alembic commands ###
